name: Reusable workflow docker-build-scan-push

on:
  workflow_call:
    inputs:
      DOTNET_VERSION:
        required: true
        type: string
        default: ""
  
    secrets:
      AZURE_CLIENT_ID:
        required: false
  
        

jobs:

  image:
    name: ACR Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      # SBOM ACR Image Report
      - name: SBOM Docker Image
        uses: ./sbom-report-generation@release
        with:
          # Trivy Scanning
          # TRIVY_FORMAT: ${{ inputs.TRIVY_FORMAT }}
          # TRIVY_OUTPUT_FILE: ${{ inputs.TRIVY_OUTPUT_FILE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


